language: generic

sudo: required  
services:
  - docker 

before_install:
  - docker build -t molaniyi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true molaniyi/docker-react npm run test